In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split 
 
df = pd.read_csv("iris.csv") 
 
(train_set, test_set) = train_test_split(df.values, train_size=0.7, 
random_state=278784)


In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set()

In [3]:
train_inputs = train_set[:, 0:4]
train_classes = train_set[:, 4]
test_inputs = test_set[:, 0:4]
test_classes = test_set[:, 4]

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(train_inputs)

train_inputs = scaler.transform(train_inputs)
test_inputs = scaler.transform(test_inputs)

In [7]:

for k in [3, 5, 11]:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(train_inputs, train_classes)
    knn_pred = knn.predict(test_inputs)
    knn_acc = knn.score(test_inputs, test_classes)
    print(knn_acc)
    knn_cm = confusion_matrix(test_classes, knn_pred)
    print("KNN, k=", k)
    print("Accuracy:", knn_acc)
    print("Confusion matrix:\n", knn_cm, "\n\n")

0.9333333333333333
KNN, k= 3
Accuracy: 0.9333333333333333
Confusion matrix:
 [[15  0  0]
 [ 0 13  1]
 [ 0  2 14]] 


0.9777777777777777
KNN, k= 5
Accuracy: 0.9777777777777777
Confusion matrix:
 [[15  0  0]
 [ 0 14  0]
 [ 0  1 15]] 


0.9777777777777777
KNN, k= 11
Accuracy: 0.9777777777777777
Confusion matrix:
 [[15  0  0]
 [ 0 14  0]
 [ 0  1 15]] 




In [6]:
from sklearn.naive_bayes import GaussianNB

# Build a Gaussian Classifier
model = GaussianNB()

# Model training
model.fit(train_inputs, train_classes)

# Predict Output
predicted = model.predict(test_inputs)

acc = accuracy_score(predicted, test_classes)
print(acc)

0.9333333333333333


Najlepsze wyniki dają 5NN i 11NN, a reszta takie same wyniki. Dokładność nie daje nam jednoznacznych wniosków. 